---

- name: Assertions
  ansible.builtin.assert:
    that:
      - windows_features is defined

- name: Install windows features
  ansible.windows.win_feature:
    name: "{{ windows_feature.name }}"
    state: "{{ windows_feature.state | default('present') }}"
    include_management_tools: "{{ windows_feature.include_management_tools | default(omit) }}"
    include_sub_features: "{{ windows_feature.include_sub_features | default(omit) }}"
    source: "{{ windows_feature.source | default(omit) }}"
  loop: "{{ windows_features }}"
  loop_control:
    loop_var: windows_feature
    label: "{{ windows_feature.name }}"
  register: __win_features

- name: Show new features installed
  ansible.builtin.debug:
    msg: "{{ __win_features.results | json_query('[].feature_result[].display_name') | sort }}"

- name: Reboot if required
  ansible.windows.win_reboot:
  when:
    - True in (__win_features.results | json_query('[].reboot_required'))
    - not windows_features_skip_reboot | bool
